from django.conf.urls import url
from project import views

urlpatterns = [
    url(r'^project-summary/$', views.ProjectSummaryView.as_view(), name='all_project_summary'),
    url(r'^ajax_add_summary/$', views.summaryadd, name='ajax_add_summary'),
    url(r'^ajax_get_project_summary/$', views.getProjectSummary, name='ajax_get_project_summary'),
    url(r'^project-summary-detail/(?P<pk>[0-9]+)/$', views.ProjectDetailView.as_view(), name='project_summary_detail'),
    url(r'^ajax_update_summary/$', views.UpdateSummary, name='ajax_update_summary'),
    url(r'^ajax_delete_summary/$', views.summarydelete, name='ajax_delete_summary'),
    url(r'^ajax_all_summary/$', views.ajax_summarys, name='ajax_all_summary'),
    url(r'^ajax_filter_summary/$', views.ajax_summarys_filter, name='ajax_filter_summary'),
    url(r'^ajax_add_bom/$', views.bomadd, name='ajax_add_bom'),
    url(r'^ajax_add_do/$', views.doadd, name='ajax_add_do'),
    url(r'^ajax_add_do_doc/$', views.dodocadd, name='ajax_add_do_doc'),
    url(r'^ajax_add_team/$', views.teamadd, name='ajax_add_team'),
    url(r'^ajax_get_team/$', views.getTeam, name='ajax_get_team'),
    url(r'^ajax_delete_team/$', views.deleteTeam, name='ajax_delete_team'),
    url(r'^ajax_export_team/(?P<projectid>[^/]+)$', views.ajax_export_team, name='ajax_export_team'),
    url(r'^ajax_export_bom/(?P<projectid>[^/]+)$', views.ajax_export_bom, name='ajax_export_bom'),
    url(r'^ajax_export_siteprogress/(?P<projectid>[^/]+)$', views.ajax_export_siteprogress, name='ajax_export_siteprogress'),
    url(r'^ajax_all_mandays/$', views.ajax_all_mandays, name='ajax_all_mandays'),
    url(r'^ajax_filter_mandays/$', views.ajax_filter_mandays, name='ajax_filter_mandays'),
    url(r'^ajax_check_donumber/$', views.check_do_number, name='ajax_check_donumber'),
    url(r'^ajax_add_proj_file/$', views.ajax_add_proj_file, name='ajax_add_proj_file'),
    url(r'^ajax_delete_file/$', views.deleteFile, name='ajax_delete_file'),
    url(r'^ajax_delete_do/$', views.deleteDo, name='ajax_delete_do'),
    url(r'^project-detail/(?P<pk>[0-9]+)/delivery-order-detail/(?P<dopk>[0-9]+)/$', views.DoDetailView.as_view(), name='project_do_detail'),
    url(r'^ajax_check_srnumber/$', views.check_sr_number, name='ajax_check_srnumber'),
    url(r'^ajax_add_sr/$', views.sradd, name='ajax_add_sr'),
    url(r'^ajax_delete_sr/$', views.deleteSR, name='ajax_delete_sr'),
    url(r'^ajax_check_pcnumber/$', views.check_pc_number, name='ajax_check_pcnumber'),
    url(r'^ajax_delete_pc/$', views.deletePc, name='ajax_delete_pc'),
    url(r'^ajax_add_pc/$', views.pcadd, name='ajax_add_pc'),
    url(r'^project-detail/(?P<pk>[0-9]+)/service-report-detail/(?P<srpk>[0-9]+)/$', views.SrDetailView.as_view(), name='project_sr_detail'),
    url(r'^project-detail/(?P<pk>[0-9]+)/progress-claim-detail/(?P<pcpk>[0-9]+)/$', views.PcDetailView.as_view(), name='project_pc_detail'),
    url(r'^ajax_pc_item_add/$', views.pcItemAdd, name='ajax_pc_item_add'),
    url(r'^ajax_delete_progress_item/$', views.deletePCItem, name='ajax_delete_progress_item'),
    url(r'^ajax_delete_service_item/$', views.deleteSRItem, name='ajax_delete_service_item'),
    url(r'^ajax_delete_delivery_item/$', views.deleteDOItem, name='ajax_delete_delivery_item'),
    url(r'^ajax_sr_item_add/$', views.srItemAdd, name='ajax_sr_item_add'),
    url(r'^ajax_do_item_add/$', views.doItemAdd, name='ajax_do_item_add'),
    url(r'^ajax_get_do_item/$', views.getDoItem, name='ajax_get_do_item'),
    url(r'^ajax_get_sr_item/$', views.getSrItem, name='ajax_get_sr_item'),
    url(r'^ajax_get_pc_item/$', views.getPcItem, name='ajax_get_pc_item'),
    url(r'^ajax_export_do_item/(?P<projectid>[^/]+)/(?P<doid>[^/]+)/$', views.ajax_export_do_item, name='ajax_export_do_item'),
    url(r'^ajax_export_sr_item/(?P<projectid>[^/]+)/(?P<srid>[^/]+)/$', views.ajax_export_sr_item, name='ajax_export_sr_item'),
    url(r'^ajax_update_delivery_order/$', views.UpdateDeliveryOrder, name='ajax_update_delivery_order'),
    url(r'project-detail/(?P<pk>[0-9]+)/delivery-detail/(?P<dopk>[0-9]+)/signature-create/$', views.DoSignatureCreate.as_view(), name='do_signature_create'),
    url(r'project-detail/(?P<pk>[0-9]+)/delivery-detail/(?P<dopk>[0-9]+)/signature-update/(?P<signpk>[0-9]+)/$', views.DoSignatureUpdate.as_view(), name='do_signature_update'),
    url(r'project-detail/(?P<pk>[0-9]+)/service-detail/(?P<srpk>[0-9]+)/signature-create/$', views.SrSignatureCreate.as_view(), name='sr_signature_create'),
    url(r'project-detail/(?P<pk>[0-9]+)/service-detail/(?P<srpk>[0-9]+)/signature-update/(?P<signpk>[0-9]+)/$', views.SrSignatureUpdate.as_view(), name='sr_signature_update'),
    url(r'project-detail/(?P<pk>[0-9]+)/progress-detail/(?P<pcpk>[0-9]+)/signature-create/$', views.PcSignatureCreate.as_view(), name='pc_signature_create'),
    url(r'project-detail/(?P<pk>[0-9]+)/progress-detail/(?P<pcpk>[0-9]+)/signature-update/(?P<signpk>[0-9]+)/$', views.PcSignatureUpdate.as_view(), name='pc_signature_update'),
    url(r'^ajax_delete_bom/$', views.deleteBom, name='ajax_delete_bom'),
    url(r'^project-detail/(?P<pk>[0-9]+)/bom-log-detail/(?P<bompk>[0-9]+)/$', views.BomDetailView.as_view(), name='project_bom_log_detail'),
    url(r'^ajax_add_bom_log/$', views.bomlogadd, name='ajax_add_bom_log'),
    url(r'^ajax_add_sub_item/$', views.subitemadd, name='ajax_add_sub_item'),
    url(r'^ajax_get_item/$', views.getItem, name='ajax_get_item'),
    url(r'^ajax_add_item/$', views.itemadd, name='ajax_add_item'),
    url(r'^ajax_get_pro_uom/$', views.getItemUom, name='ajax_get_pro_uom'),
    url(r'^ajax_delete_service_item/$', views.deleteSRItem, name='ajax_delete_service_item'),
    url(r'^ajax_add_site_progress_log/$', views.siteprogressadd, name='ajax_add_site_progress_log'),
    url(r'^ajax_get_site_progress/$', views.getSiteProgress, name='ajax_get_site_progress'),
    url(r'^ajax_delete_site_progress/$', views.sitedelete, name='ajax_delete_site_progress'),
    url(r'^ajax_add_toolbox_item/$', views.toolboxitemadd, name='ajax_add_toolbox_item'),
    url(r'^ajax_get_toolbox_item/$', views.getToolBoxItem, name='ajax_get_toolbox_item'),
    url(r'^ajax_delete_tbm_item/$', views.tbmitemdelete, name='ajax_delete_tbm_item'),
    url(r'^ajax_get_bom/$', views.getBom, name='ajax_get_bom'),
    url(r'^ajax_add_sr_doc/$', views.srdocadd, name='ajax_add_sr_doc'),
    url(r'^ajax_add_pc_doc/$', views.pcdocadd, name='ajax_add_pc_doc'),
    url(r'^ajax_filter_description/$', views.ajax_filter_description, name='ajax_filter_description'),
    url(r'^ajax_update_service_report/$', views.ajax_update_service_report, name='ajax_update_service_report'),
    url(r'^ajax_update_progress_claim/$', views.ajax_update_progress_claim, name='ajax_update_progress_claim'),

    url(r'^ajax-export-project/$', views.ajax_export_project, name='ajax-export-project'),
    url(r'^ajax-import-project/$', views.ajax_import_project, name='ajax-import-project'),
    #OT Part
    url(r'^project-ot/$', views.ProjectOTView.as_view(), name='all_project_ot'),
    url(r'^ajax_add_ot/$', views.otadd, name='ajax_add_ot'),
    url(r'^ajax_get_project_ot/$', views.getProjectOt, name='ajax_get_project_ot'),
    url(r'^ajax_delete_ot/$', views.otdelete, name='ajax_delete_ot'),
    # url(r'^ajax_check_otno/$', views.check_ot_number, name='ajax_check_otno'),
    url(r'^ajax_all_projectot/$', views.ajax_projectots, name='ajax_all_projectot'),
    url(r'^ajax_filter_projectot/$', views.ajax_projectots_filter, name='ajax_filter_projectot'),
    url(r'^ajax_get_projectname/$', views.ajax_get_projectname, name='ajax_get_projectname'),
    url(r'^approved-ot/$', views.approvedOTView.as_view(), name='all_approved_ot'),

    url(r'^ajax-export-projectot/$', views.ajax_export_projectot, name='ajax-export-projectot'),
    url(r'^ajax-import-projectot/$', views.ajax_import_projectot, name='ajax-import-projectot'),

    url(r'^export_do_pdf/(?P<value>\w+)/$', views.exportDoPDF, name='export_do_pdf'),
    url(r'^export_sr_pdf/(?P<value>\w+)/$', views.exportSrPDF, name='export_sr_pdf'),
    url(r'^export_pc_pdf/(?P<value>\w+)/$', views.exportPcPDF, name='export_pc_pdf'),

    url(r'^ajax_add_delivery_sign/$', views.deliverysignadd, name='ajax_add_delivery_sign'),
    url(r'^ajax_get_delivery_sign/$', views.getDeliverySign, name='ajax_get_delivery_sign'),

    url(r'^ajax_add_service_sign/$', views.servicesignadd, name='ajax_add_service_sign'),
    url(r'^ajax_get_service_sign/$', views.getServiceSign, name='ajax_get_service_sign'),
    
]
